### ISSUE TITLE
Pull requests are not being loaded.

### ISSUE THREAD

**Issue by alvarovillafane** [menubar-apps/issues#3]
**Describe the bug**
Hi, I bought the pull bar pro (version 1.8) and followed the instructions by creating the personal token added the auth in the app, but the pull Request are not coming through.

Everything is marked as 0.
Would you mind helping me here? Thanks!

**To Reproduce**
1. Go to app store
2. Install pull bar pro
3. Create github personal token with PR + metadata permissions
4. Add your email + personal token as auth in pull bar pro
5. The PRs are not coming through

I'm the admin so didn't need to authorise the token in the organisation. And is enabled.

**Expected behavior**
Should load the PR to review

**Desktop (please complete the following information):**
 - OS:  Sonoma 14.6.1

**Additional context**
Same problems here https://github.com/menubar-apps/PullBar/issues/34

**Comment by streetturtle** [comment]
Hi! 
Just to confirm, you're using the fine-grained token, right?

If so, could you please try to select "none" in the Build Information section in Preferences. If it helped, then you're missing the Contents Repositore permission (for some reason access to commit statuses fall under this permission).

**Comment by alvarovillafane** [comment]
<img width="700" alt="Screenshot 2024-11-29 at 10 40 59 AM" src="https://github.com/user-attachments/assets/b03075a2-61b8-4980-88cd-da4da9451f66">

Thanks @streetturtle yes, is `none` already and I'm using the fine-grained token.
Nothing changed, not sure what I should try next.

**Comment by streetturtle** [comment]
That's strange. Can you double-check the username in the Authentication tab, maybe there is an extra space, or something?
What permissions your token has? Does it look like this: 
<img width="806" alt="Screenshot 2024-11-28 at 8 20 11 PM" src="https://github.com/user-attachments/assets/78a90587-8089-40d8-82b9-d562eb0f38d7">

**Comment by alvarovillafane** [comment]
figure it out @streetturtle , was using my email instead of my handle as the username.
All good, but would be useful if the app would throw an error message on those cases.

Cheers

**Comment by streetturtle** [comment]
It's a very good point! I'll add a validation to the username field, to notify users not to use the email. 
Happy it works now!
